### ISSUE TITLE
I've got empty tag..

### ISSUE THREAD

**Issue by hopewise** [leolimasa/cereal#1] opened 2014-08-08 05:26 UTC
As I tried to use the library, here is my implementation:

```
            var xml = new XMLSerializer();
    xml.types.set("version", "com.clientside.Version");
    var version:Version = new Version();
    version.versionNumber = 1.09;
    version.url = "http://www.dcaclab.com/";
    var output:String = xml.deflate(version);

    trace(output);
```

But, what I got is just:

```
<version/>
```

The class is:

```
class Version
{

public function new() 
{

}
public var versionNumber:Float;
public var url:String;


}
```

**Comment by leolimasa** [comment] 2014-08-09 02:46
Unfortunately, I could not reproduce. Here is what I used:

_com/clientside/Version.hx_

```
package com.clientside;

class Version
{

  public function new()
  {

  }
  public var versionNumber:Float;
  public var url:String;

}
```

_Test.hx_

```
package;

import com.clientside.Version;
import cereal.XMLSerializer;

class Test {
  public function new() {
}

public static function main() {
    var xml = new XMLSerializer();
    xml.types.set("version", "com.clientside.Version");
    var version:Version = new Version();
    version.versionNumber = 1.09;
    version.url = "http://www.dcaclab.com/";
    var output:String = xml.deflate(version);
    trace(output);
 }
```

   }

The output is:

```
Test.hx:17: <version versionNumber="1.09" url="http://www.dcaclab.com/"/>
```

And the compilation command:

```
 haxe -main Test -lib cereal -neko test.n
```

What is the target and cereal version you are using?

**Comment by hopewise** [comment] 2014-08-09 09:33
I tried to target windows, using openFL, I have cereal 0.0.4

On Sat, Aug 9, 2014 at 5:46 AM, submain notifications@github.com wrote:

> Unfortunately, I could not reproduce. Here is what I used:
> 
> _com/clientside/Version.hx_
> 
> package com.clientside;
> 
> class Version
> {
> 
>   public function new()
>   {
> 
>   }
>   public var versionNumber:Float;
>   public var url:String;
> 
> }
> 
> _Test.hx_
> 
> package;
> 
> import com.clientside.Version;
> import cereal.XMLSerializer;
> 
> class Test {
>   public function new() {
> }
> 
> public static function main() {
>     var xml = new XMLSerializer();
>     xml.types.set("version", "com.clientside.Version");
>     var version:Version = new Version();
>     version.versionNumber = 1.09;
>     version.url = "http://www.dcaclab.com/";
>     var output:String = xml.deflate(version);
>     trace(output);
>  }
> 
> }
> 
> The output is:
> 
> Test.hx:17: <version versionNumber="1.09" url="http://www.dcaclab.com/"/>
> 
> And the compilation command:
> 
>  haxe -main Test -lib cereal -neko test.n
> 
> What is the target and cereal version you are using?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/submain/cereal/issues/1#issuecomment-51675034.

## 

## 

## Kind Regards,

Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by leolimasa** [comment] 2014-09-15 02:57
Are you still seeing this issue? If not, I'll be closing.

**Closed as completed** 2014-09-20 23:34 UTC
